Update AUTHORS file
Use libtool to link the library.  Might as well use libtool's
weird versioning scheme too, as this is the first shipping nasal
shared library.

Add a tiny (one 4-line function) readline library.  Write
an "interactive" module that implements a simple
interpreter (none of the fancy features from int-nasal yet), and
invoke that from the driver when no script is specified.

Add a few convenience functions to the regex module.

Print a warning when the wrapper script can't find a binary.

Have a NULL args argument to naCall() mean "don't do argument
setup" instead of "zero arguments".

Note the cvsweb interface on the web site.

diff --git a/nasal/src/nasal b/nasal/src/nasal
--- a/nasal/src/nasal
+++ b/nasal/src/nasal
@@ -19,4 +19,9 @@ if [ ! -d "$LIBDIR" ]; then
     LIBDIR="$BINDIR/../lib"
 fi
 
-exec "$BINDIR/nasal-bin" "$LIBDIR/driver.nas" "$@"
+if [ -x "$BINDIR/nasal-bin" ]; then
+    exec "$BINDIR/nasal-bin" "$LIBDIR/driver.nas" "$@"
+fi
+
+echo "Cannot locate nasal-bin interpreter."
+exit 1
